# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Climatematch Impact Scholars Program
author: Climatematch
logo: info/images/cma_logo.png
only_build_toc_files: true

sphinx:
  config:
    language: en
    myst_heading_anchors: 2
    html_theme_options:
      announcement: "<font size = '6'>üåçüåéüåè We are looking for mentors with experience in climate research! <br> <a href='https://airtable.com/appLHqbcnAQ1EUO47/shrDDmUFZ594k6KQ0' style='color:#f0ba7d;'><b>APPLY HERE!</b></a></font>"  
      logo:
        text: Climatematch Impact Scholars Program 
    html_sidebars:
      '**': [navbar-logo.html, search-field.html, sbt-sidebar-nav.html]


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: impactscholars.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ClimateMatchAcademy/impact-scholars  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                   : info/images/cma_logo.png  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : false # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true
  extra_footer : |
    <div>
    <a href="http://creativecommons.org/licenses/by/4.0/"><img src="https://i.creativecommons.org/l/by/4.0/88x31.png"></a>
    <a href="https://opensource.org/licenses/BSD-3-Clause"><img src="https://camo.githubusercontent.com/9b9ea65d95c9ef878afa1987df65731d47681336/68747470733a2f2f696d672e736869656c64732e696f2f707970692f6c2f736561626f726e2e737667"></a>
    The contents of this repository are shared under the <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
    Software elements are additionally licensed under the <a href="https://opensource.org/licenses/BSD-3-Clause">BSD (3-Clause) License</a>.
    </div>
